//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.12 at 03:21:52 PM WEST 
//


package ensa.ebanking.accountservice.soap.request.creanceslist;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="creance" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="creanceStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="creancier">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="creancierCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="serviceProvider">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creance"
})
@XmlRootElement(name = "CreancesListResponse")
public class CreancesListResponse {

    protected List<CreancesListResponse.Creance> creance;

    /**
     * Gets the value of the creance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreancesListResponse.Creance }
     * 
     * 
     */
    public List<CreancesListResponse.Creance> getCreance() {
        if (creance == null) {
            creance = new ArrayList<CreancesListResponse.Creance>();
        }
        return this.creance;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="creanceStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="creancier">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="creancierCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="serviceProvider">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "code",
        "dueDate",
        "amount",
        "creanceStatus",
        "creancier"
    })
    public static class Creance {

        protected long code;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar dueDate;
        protected double amount;
        @XmlElement(required = true)
        protected String creanceStatus;
        @XmlElement(required = true)
        protected CreancesListResponse.Creance.Creancier creancier;

        /**
         * Gets the value of the code property.
         * 
         */
        public long getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         */
        public void setCode(long value) {
            this.code = value;
        }

        /**
         * Gets the value of the dueDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDueDate() {
            return dueDate;
        }

        /**
         * Sets the value of the dueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDueDate(XMLGregorianCalendar value) {
            this.dueDate = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         */
        public double getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         */
        public void setAmount(double value) {
            this.amount = value;
        }

        /**
         * Gets the value of the creanceStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreanceStatus() {
            return creanceStatus;
        }

        /**
         * Sets the value of the creanceStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreanceStatus(String value) {
            this.creanceStatus = value;
        }

        /**
         * Gets the value of the creancier property.
         * 
         * @return
         *     possible object is
         *     {@link CreancesListResponse.Creance.Creancier }
         *     
         */
        public CreancesListResponse.Creance.Creancier getCreancier() {
            return creancier;
        }

        /**
         * Sets the value of the creancier property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreancesListResponse.Creance.Creancier }
         *     
         */
        public void setCreancier(CreancesListResponse.Creance.Creancier value) {
            this.creancier = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="creancierCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="serviceProvider">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "code",
            "name",
            "creancierCategory",
            "serviceProvider"
        })
        public static class Creancier {

            protected long code;
            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String creancierCategory;
            @XmlElement(required = true)
            protected CreancesListResponse.Creance.Creancier.ServiceProvider serviceProvider;

            /**
             * Gets the value of the code property.
             * 
             */
            public long getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             */
            public void setCode(long value) {
                this.code = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the creancierCategory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCreancierCategory() {
                return creancierCategory;
            }

            /**
             * Sets the value of the creancierCategory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCreancierCategory(String value) {
                this.creancierCategory = value;
            }

            /**
             * Gets the value of the serviceProvider property.
             * 
             * @return
             *     possible object is
             *     {@link CreancesListResponse.Creance.Creancier.ServiceProvider }
             *     
             */
            public CreancesListResponse.Creance.Creancier.ServiceProvider getServiceProvider() {
                return serviceProvider;
            }

            /**
             * Sets the value of the serviceProvider property.
             * 
             * @param value
             *     allowed object is
             *     {@link CreancesListResponse.Creance.Creancier.ServiceProvider }
             *     
             */
            public void setServiceProvider(CreancesListResponse.Creance.Creancier.ServiceProvider value) {
                this.serviceProvider = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "code",
                "image",
                "name",
                "surname",
                "phoneNumber"
            })
            public static class ServiceProvider {

                protected long code;
                @XmlElement(required = true)
                protected String image;
                @XmlElement(required = true)
                protected String name;
                @XmlElement(required = true)
                protected String surname;
                @XmlElement(required = true)
                protected String phoneNumber;

                /**
                 * Gets the value of the code property.
                 * 
                 */
                public long getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 */
                public void setCode(long value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the image property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getImage() {
                    return image;
                }

                /**
                 * Sets the value of the image property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setImage(String value) {
                    this.image = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the surname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSurname() {
                    return surname;
                }

                /**
                 * Sets the value of the surname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSurname(String value) {
                    this.surname = value;
                }

                /**
                 * Gets the value of the phoneNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPhoneNumber() {
                    return phoneNumber;
                }

                /**
                 * Sets the value of the phoneNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPhoneNumber(String value) {
                    this.phoneNumber = value;
                }

            }

        }

    }

}
