//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.10 at 11:21:44 PM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ebanking.ensa/accountservice/Soap/Request/CreanciersList/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ensa.ebanking.accountservice.soap.request.creancierslist;
